# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "71e800405c3122df8cf8c81daaa6b6b6"
application_url = "https://main-pink-phi.vercel.app"
embedded = true
name = "rebel-custom-app"

[webhooks]
api_version = "2026-10"

[access_scopes]
scopes = "read_customers,read_metaobject_definitions,read_metaobjects,read_orders,read_products,write_metaobject_definitions,write_metaobjects,write_orders,write_products"

[auth]
redirect_urls = [
  "https://shopify.dev/apps/default-app-home/api/auth",
  "https://main-pink-phi.vercel.app/auth/callback",
  "https://main-pink-phi.vercel.app/auth/shopify/callback"
]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[[extensions]]
name = "Theme Extensions"
handle = "cart-ui"
type = "theme"
